apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: customercare
  template:
    metadata:
      labels:
        app: customercare
    spec:
      containers:
      - name: customercare
        image: nginx:1.15.1
        ports:
        - containerPort: 80
        resources:         
          limits:          
            cpu: 50m        
            memory: "55Mi"
