apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: sales-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-replica
  template:
    metadata:
      labels:
        app: my-replica
    spec:
      containers:
      - name: nginx-rs
        image: nginx:latest
        resources:
          limits:
            cpu: 200m
            memory: "105Mi"
